SATELLITE_NAME = 'ISS (ZARYA)'
OUTPUT_PATH = "output/satellite_position.html"
CELESTRACK_SATELLITE_SOURCES = {
'Last 30 Days\' Launches': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=last-30-days&FORMAT=tle',
'Space Stations': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=tle',
'100 Brightest': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=visual&FORMAT=tle',
'Active Satellites': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=tle',
'Analyst Satellites': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=analyst&FORMAT=tle',
'Russian ASAT Test Debris (COSMOS 1408)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=cosmos-1408-debris&FORMAT=tle',
'Chinese ASAT Test Debris (FENGYUN 1C)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=fengyun-1c-debris&FORMAT=tle',
'IRIDIUM 33 Debris': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=iridium-33-debris&FORMAT=tle',
'COSMOS 2251 Debris': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=cosmos-2251-debris&FORMAT=tle',
'Weather': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=weather&FORMAT=tle',
'NOAA': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=noaa&FORMAT=tle',
'GOES': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=goes&FORMAT=tle',
'Earth Resources': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=resource&FORMAT=tle',
'Search & Rescue (SARSAT)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=sarsat&FORMAT=tle',
'Disaster Monitoring (DMC)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=dmc&FORMAT=tle',
'Tracking and Data Relay Satellite System (TDRSS)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=tdrss&FORMAT=tle',
'ARGOS Data Collection System': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=argos&FORMAT=tle',
'Planet': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=planet&FORMAT=tle',
'Spire': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=spire&FORMAT=tle',
'Active Geosynchronous': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=geo&FORMAT=tle',
'GEO Protected Zone': 'https://celestrak.org/NORAD/elements/gp.php?SPECIAL=gpz&FORMAT=tle',
'GEO Protected Zone Plus': 'https://celestrak.org/NORAD/elements/gp.php?SPECIAL=gpz-plus&FORMAT=tle',
'Intelsat': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=intelsat&FORMAT=tle',
'SES': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=ses&FORMAT=tle',
'Eutelsat': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=eutelsat&FORMAT=tle',
'Iridium': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=iridium&FORMAT=tle',
'Iridium NEXT': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=iridium-NEXT&FORMAT=tle',
'Starlink': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=starlink&FORMAT=tle',
'OneWeb': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=oneweb&FORMAT=tle',
'Orbcomm': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=orbcomm&FORMAT=tle',
'Globalstar': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=globalstar&FORMAT=tle',
'Swarm': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=swarm&FORMAT=tle',
'Amateur Radio': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=amateur&FORMAT=tle',
'SatNOGS': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=satnogs&FORMAT=tle',
'Experimental Comm': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=x-comm&FORMAT=tle',
'Other Comm': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=other-comm&FORMAT=tle',
'Gorizont': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=gorizont&FORMAT=tle',
'Raduga': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=raduga&FORMAT=tle',
'Molniya': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=molniya&FORMAT=tle',
'GNSS': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=gnss&FORMAT=tle',
'GPS Operational': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=gps-ops&FORMAT=tle',
'GLONASS Operational': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=glo-ops&FORMAT=tle',
'Galileo': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=galileo&FORMAT=tle',
'Beidou': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=beidou&FORMAT=tle',
'Satellite-Based Augmentation System (WAAS/EGNOS/MSAS)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=sbas&FORMAT=tle',
'Navy Navigation Satellite System (NNSS)': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=nnss&FORMAT=tle',
'Russian LEO Navigation': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=musson&FORMAT=tle',
'Space & Earth Science': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=science&FORMAT=tle',
'Geodetic': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=geodetic&FORMAT=tle',
'Engineering': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=engineering&FORMAT=tle',
'Education': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=education&FORMAT=tle',
'Miscellaneous Military': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=military&FORMAT=tle',
'Radar Calibration': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=radar&FORMAT=tle',
'Cubesats': '',
'Other Satellites': 'https://celestrak.org/NORAD/elements/gp.php?GROUP=other&FORMAT=tle'
}