SATELLITE_NAME = 'ISS (ZARYA)'
OUTPUT_PATH = "satellite_position.html"
FORMAT = 'tle'
CELESTRACK_SATELLITE_GROUPS = {
    'Last 30 Days\' Launches': 'last-30-days',
    'Space Stations': 'stations',
    '100 Brightest': 'visual',
    'Active Satellites': 'active',
    'Analyst Satellites': 'analyst',
    'Russian ASAT Test Debris (COSMOS 1408)': 'cosmos-1408-debris',
    'Chinese ASAT Test Debris (FENGYUN 1C)': 'fengyun-1c-debris',
    'IRIDIUM 33 Debris': 'iridium-33-debris',
    'COSMOS 2251 Debris': 'cosmos-2251-debris',
    'Weather': 'weather',
    'NOAA': 'noaa',
    'GOES': 'goes',
    'Earth Resources': 'resource',
    'Search & Rescue (SARSAT)': 'sarsat',
    'Disaster Monitoring (DMC)': 'dmc',
    'Tracking and Data Relay Satellite System (TDRSS)': 'tdrss',
    'ARGOS Data Collection System': 'argos',
    'Planet': 'planet',
    'Spire': 'spire',
    'Active Geosynchronous': 'geo',
    'GEO Protected Zone': 'gpz',
    'GEO Protected Zone Plus': 'gpz-plus',
    'Intelsat': 'intelsat',
    'SES': 'ses',
    'Eutelsat': 'eutelsat',
    'Iridium': 'iridium',
    'Iridium NEXT': 'iridium-NEXT',
    'Starlink': 'starlink',
    'OneWeb': 'oneweb',
    'Orbcomm': 'orbcomm',
    'Globalstar': 'globalstar',
    'Swarm': 'swarm',
    'Amateur Radio': 'amateur',
    'SatNOGS': 'satnogs',
    'Experimental Comm': 'x-comm',
    'Other Comm': 'other-comm',
    'Gorizont': 'gorizont',
    'Raduga': 'raduga',
    'Molniya': 'molniya',
    'GNSS': 'gnss',
    'GPS Operational': 'gps-ops',
    'GLONASS Operational': 'glo-ops',
    'Galileo': 'galileo',
    'Beidou': 'beidou',
    'Satellite-Based Augmentation System (WAAS/EGNOS/MSAS)': 'sbas',
    'Navy Navigation Satellite System (NNSS)': 'nnss',
    'Russian LEO Navigation': 'musson',
    'Space & Earth Science': 'science',
    'Geodetic': 'geodetic',
    'Engineering': 'engineering',
    'Education': 'education',
    'Miscellaneous Military': 'military',
    'Radar Calibration': 'radar',
    'Cubesats': 'cubesat',
    'Other Satellites': 'other'
}